### ISSUE TITLE
Ask write permissions to the LiMe network-profiles

### ISSUE THREAD

**Issue by nicopace** [sbmesh/sbmesh-profiles#2]
Hi!
I'm part of the development team of LibreMesh.
We have a repository for these profiles that are collective (you can get write permissions), so ... would invite you to merge to it:
https://github.com/libremesh/network-profiles

Let me know!

Regards!!!

**Comment by raylas** [comment]
We would love to merge to your community repo, @nicopace ! We planned to all along, just wanted to get something running quickly at the time!

**Comment by nicopace** [comment]
Better sooner than later! everyone benefits ;)

**Comment by raylas** [comment]
@nicopace I've opened a pull request! Thanks again.
